// <auto-generated />
using Advertising.Dal.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AdvertisingService.Migrations.AdvertisingService
{
    [DbContext(typeof(AdvertisingServiceContext))]
    partial class AdvertisingServiceContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Common.Entity.AdvertisingCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CategoryName")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("AdvertisingCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryName = "Audi"
                        },
                        new
                        {
                            Id = 2,
                            CategoryName = "BMW"
                        },
                        new
                        {
                            Id = 3,
                            CategoryName = "Volkswagen"
                        },
                        new
                        {
                            Id = 4,
                            CategoryName = "Volvo"
                        },
                        new
                        {
                            Id = 5,
                            CategoryName = "Lada"
                        },
                        new
                        {
                            Id = 6,
                            CategoryName = "Citroen"
                        },
                        new
                        {
                            Id = 7,
                            CategoryName = "Land Rover"
                        },
                        new
                        {
                            Id = 8,
                            CategoryName = "Nissan"
                        });
                });

            modelBuilder.Entity("Common.Entity.AdvertisingModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AdvertisingCategoryId");

                    b.Property<string>("AdvertisingName")
                        .IsRequired();

                    b.Property<string>("ImagePath");

                    b.Property<string>("ItemPrice");

                    b.Property<string>("Text")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Advertisings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AdvertisingCategoryId = 1,
                            AdvertisingName = "Audi A1",
                            ImagePath = "http://cdn.motorpage.ru/Photos/800/1E66.jpg",
                            ItemPrice = "21 000 р.",
                            Text = "Авто 2013 года. Оригинальный пробег подтвержденный сервисными документами. +375293585471"
                        },
                        new
                        {
                            Id = 2,
                            AdvertisingCategoryId = 1,
                            AdvertisingName = "Audi A4 B7",
                            ImagePath = "https://media.motorlandby.ru/car/540731/4.jpg",
                            ItemPrice = "18 000 р.",
                            Text = "Авто 2006 г. Автомобиль в отличном состоянии ,работает как Часы. +375445412518"
                        },
                        new
                        {
                            Id = 3,
                            AdvertisingCategoryId = 2,
                            AdvertisingName = "BMW X1 E84 X-drive",
                            ImagePath = "https://s31.wheelsage.org/format/picture/picture-preview-large/b/bmw/x1_xdrive20d/bmw_x1_xdrive20d_38_016000a20c770898.jpg",
                            ItemPrice = "31 000 р.",
                            Text = "2009 г. Отличная комплектация. АКПП без проблем. Салон кожа. Адаптивный свет. +375297665131"
                        },
                        new
                        {
                            Id = 4,
                            AdvertisingCategoryId = 2,
                            AdvertisingName = "BMW X5",
                            ImagePath = "https://s-turbo.by/images/shop/products/full_nakladka-perednego-bampera-ag181-bmw-x5-e53-102003-102006.jpg",
                            ItemPrice = "13 000 р.",
                            Text = "Авто 2003 г. Хорошее состояние +375297654131"
                        },
                        new
                        {
                            Id = 5,
                            AdvertisingCategoryId = 3,
                            AdvertisingName = "Volkswagen Tiguan I 2013",
                            ImagePath = "https://img.automoto.ua/auto/Volkswagen-Tiguan-ne_ukazan-none-2013-6b4-17098255.jpeg",
                            ItemPrice = "25 000 р.",
                            Text = "Авто в отличном состоянии +375297694131"
                        },
                        new
                        {
                            Id = 6,
                            AdvertisingCategoryId = 3,
                            AdvertisingName = "Volkswagen Golf VI",
                            ImagePath = "http://cloud.leparking.fr/2018/12/03/03/20/volkswagen-golf-vw-golf-6-r-2011-90000-km-noir_6573771276.jpg",
                            ItemPrice = "16 500 р.",
                            Text = "2011 г. +375298354131"
                        },
                        new
                        {
                            Id = 7,
                            AdvertisingCategoryId = 4,
                            AdvertisingName = "Volvo 740 TURBO, 1987",
                            ImagePath = "https://cdn.bringatrailer.com/wp-content/uploads/2019/06/1987_volvo_740_156130611409211149IMG_0804-940x597.jpg",
                            ItemPrice = "1 500 р.",
                            Text = "Для своих лет состояние идеальное +375297584937"
                        },
                        new
                        {
                            Id = 8,
                            AdvertisingCategoryId = 4,
                            AdvertisingName = "Volvo S80 I, 2001",
                            ImagePath = "https://rzpict1.blob.core.windows.net/images/480/autoscout24.nl/RZCATSNL722034F3388F/VOLVO-S80-1.jpg",
                            ItemPrice = "15 000 р.",
                            Text = "+375948374928"
                        },
                        new
                        {
                            Id = 9,
                            AdvertisingCategoryId = 5,
                            AdvertisingName = "Lada (ВАЗ) Vesta 2018",
                            ImagePath = "https://img-salon.a.tyt.by/catalog/vaz-lada/vesta/0d/1/5605696a794fc.jpeg",
                            ItemPrice = "22 000 р.",
                            Text = "Машина только с салона. +375297394815"
                        },
                        new
                        {
                            Id = 10,
                            AdvertisingCategoryId = 5,
                            AdvertisingName = "Lada (ВАЗ) Granta, 2019",
                            ImagePath = "http://cdn.motorpage.ru/Photos/800/01a9D.jpg",
                            ItemPrice = "13 000 р.",
                            Text = "Пробег 5274 км. +375338475933"
                        },
                        new
                        {
                            Id = 11,
                            AdvertisingCategoryId = 6,
                            AdvertisingName = "Citroen C3 II, 2010",
                            ImagePath = "http://www.aw.by/photos/catalog/64847_1.jpg",
                            ItemPrice = "14 000 р.",
                            Text = "Авто 2010 стаяла в гараже проюег 10 000 км за 9 лет. +375283947583"
                        },
                        new
                        {
                            Id = 12,
                            AdvertisingCategoryId = 6,
                            AdvertisingName = "Citroen C5 II, 2010",
                            ImagePath = "https://s.drom.ru/1/reviews/photos/citroen/c5/big_48587_1.jpeg",
                            ItemPrice = "16 000 р.",
                            Text = "Авто 2010 пробег 120 000. +375297483759"
                        },
                        new
                        {
                            Id = 13,
                            AdvertisingCategoryId = 7,
                            AdvertisingName = "Land Rover Range Rover III",
                            ImagePath = "https://a.d-cd.net/32ea88as-960.jpg",
                            ItemPrice = "44 000 р.",
                            Text = "2010 г. Пробез 170к. +37584938496"
                        },
                        new
                        {
                            Id = 14,
                            AdvertisingCategoryId = 7,
                            AdvertisingName = "Land Rover Discovery III SE, 2006",
                            ImagePath = "https://a.d-cd.net/0YAAAgAgCOA-960.jpg",
                            ItemPrice = "26 000 р.",
                            Text = "Машина 2006 г. Пробег 320к. +375847934942"
                        },
                        new
                        {
                            Id = 15,
                            AdvertisingCategoryId = 8,
                            AdvertisingName = "Nissan Juke YF15, 2011",
                            ImagePath = "https://image-cdn.beforward.jp/large/201707/783544/BF658797_0c8841.jpg",
                            ItemPrice = "21 000 р.",
                            Text = "С пробегом 91 000 км. Автомат +375297482759"
                        },
                        new
                        {
                            Id = 16,
                            AdvertisingCategoryId = 8,
                            AdvertisingName = "Nissan Terrano R20",
                            ImagePath = "https://s1.cdn.autoevolution.com/images/gallery/NISSANTerrano3Doors-430_10.jpg",
                            ItemPrice = "16 000 р.",
                            Text = "Авто 2003 г. 260к км. +375298475936"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
